---
# handlers file for configure-squid
- name: turn off squid_connect_any
  seboolean: 
    name: squid_connect_any
    state: no
    persistent: yes
  listen: "restart squid"

- name: restart squid
  service:
    name: squid.service
    state: restarted
  listen: "restart squid"

- name: Restart firewalld.service
  service:
    name: firewalld.service
    state: restarted
  listen: "restart firewalld"
  

 
