# Run the setup effort to build an OCP Bastion guest
- name: Create guest for OCP Bastion
  hosts: 127.0.0.1
  connection: local
  vars:
  - directory_entry: "{{ lookup('template', '{{ playbook_dir }}/local-playbooks/roles/create-guest-for-linux/templates/guest.direct.j2') }}"
  roles:
  - "{{ playbook_dir }}/local-playbooks/roles/create-guest-for-linux"

- name: Configure Squid on the OCP Bastion
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/local-playbooks/roles/configure-squid"

- name: Create a local Certificate Authority
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/local-playbooks/roles/create-local-ca"

- name: Configure apache to serve LDAP Tools
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/local-playbooks/roles/setup-ldap-tools"

- name: configure minimal dns server
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/multiarch-ci-playbooks/playbooks/examples/roles/configure-dns"

- name: configure minimal haproxy server
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/multiarch-ci-playbooks/playbooks/examples/roles/configure-haproxy"

- name: configure haproxy server to offer statistics interface
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/local-playbooks/roles/enable-haproxy-stats"

# configures minimal httpd server to serve ignition configs
- name: Configure apache to serve ignition configs
  hosts: s390x-bastion-workstation
  roles:
  - "{{ playbook_dir }}/multiarch-ci-playbooks/playbooks/examples/roles/configure-apache-ignition"
