---
# tasks file for create-guest-for-linux
- name: create a new directory entry for a Linux guest
  shell: /usr/local/bin/smcli icd -T {{ cluster_nodes[coreos_role][item].guest_name|quote }} -H {{ ocp_smapi_host|quote }} -U {{ ocp_smapi_user|quote }} -P {{ ocp_smapi_password|quote }}
  args:
    stdin: "{{ directory_entry }}"
    executable: /bin/bash

- name: write the parmfile to the reader
  shell: curl -Q "SITE FIX 132" -T /var/html/www/ignition/{{ cluster_nodes[coreos_role][item].guest_name }}.znetboot -B ftp://MAINT.BY.{{ ocp_smapi_user|quote }}:{{ ocp_smapi_password|quote }}@{{ zvm_internal_ip_address|quote }}/MAINT.200/
  args:
    warn: false

- name: IPL a Linux guest
  shell: /usr/local/bin/smcli ia -T {{ cluster_nodes[coreos_role][item].guest_name|quote }} -H {{ ocp_smapi_host|quote }} -U {{ ocp_smapi_user|quote }} -P {{ ocp_smapi_password|quote }}
  args:
    executable: /bin/bash

- name: set the real IPL device for a Linux guest
  shell: /usr/local/bin/smcli iisd -T {{ cluster_nodes[coreos_role][item].guest_name|quote }} -n 200 -H {{ ocp_smapi_host|quote }} -U {{ ocp_smapi_user|quote }} -P {{ ocp_smapi_password|quote }}
  args:
    executable: /bin/bash

