---
- name: generate httpd private key
  openssl_privatekey:
    path: /etc/pki/tls/private/httpd.pem

- name: generate httpd CSR
  openssl_csr:
    path: /etc/pki/tls/misc/httpd.csr
    privatekey_path: /etc/pki/tls/private/httpd.pem
    common_name: "ldaptools.{{ cluster_name }}.{{ cluster_base_domain }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "Red Hat Openshift PoC"
    country_name: "{{ cert_country }}"

- name: generate Certificate
  openssl_certificate:
    path: /etc/pki/tls/certs/httpd.cert
    csr_path: /etc/pki/tls/misc/httpd.csr
    ownca_path: /etc/pki/tls/certs/oqsCA.cert
    ownca_privatekey_path: /etc/pki/tls/private/oqsCA.pem
    provider: ownca

- name: install apache httpd and mod_ssl
  yum:
    name:
      - httpd
      - mod_ssl
      - php
      - php-ldap
      - php-mbstring
    state: latest

- name: install php-Smarty
  yum:
    name: https://www.rpmfind.net/linux/fedora-secondary/releases/30/Everything/s390x/os/Packages/p/php-Smarty-3.1.33-1.fc30.noarch.rpm
    state: present
  environment:
    https_proxy: http://10.2.75.44:3128

- name: define CA details for apache, SSLCertificateFile
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: "^#?SSLCertificateFile"
    line: SSLCertificateFile /etc/pki/tls/certs/httpd.cert

- name: define CA details for apache, SSLCertificateKeyFile
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: "^#?SSLCertificateKeyFile"
    line: SSLCertificateKeyFile /etc/pki/tls/private/httpd.pem

- name: define CA details for apache, SSLCertificateChainFile
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: "^#?SSLCertificateChainFile"
    line: SSLCertificateChainFile /etc/pki/tls/certs/oqsCA.cert

- name: add the Apache configuration for the LDAP tools
  blockinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    insertbefore: "</VirtualHost>"
    block: |
      Alias /password /var/www/html/self-service-password-racf-master
      Alias /ldap-sd  /var/www/html/service-desk-racf-dev-racf-full/htdocs
      <Directory "/var/www/html/self-service-password-racf-master">
        AllowOverride None
        Require all granted
      </Directory>
      <Directory "/var/www/html/self-service-password-racf-master/scripts">
        AllowOverride None
        Require all denied
      </Directory>
      <Directory "/var/www/html/service-desk-racf-dev-racf-full/htdocs">
        AllowOverride None
      #  AuthType basic
      #  AuthName "LDAP Service Desk by LTB"
      #  AuthBasicProvider ldap
      #  AuthLDAPURL ldap://zsldap1.z.stg.ibm:389/ou=z,ou=systems,o=ibm?uid
      #  Require ldap-group cn=SystemsAdmin,ou=group,ou=z,ou=systems,o=ibm
      </Directory>

- name: allow traffic at 443 for apache
  tags: firewall
  firewalld:
    service: https
    zone: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
  - internal
  - public

- name: download and unwind LDAP tools
  block:
  - name: download and unzip self-service-password
    unarchive:
      src: "https://github.com/viccross/self-service-password-racf/archive/master.zip"
      dest: "/var/www/html/"
      creates: "/var/www/html/self-service-password-racf"
      remote_src: yes
    environment:
      https_proxy: http://10.2.75.44:3128

  - name: download and unzip service-desk
    unarchive:
      src: "https://github.com/viccross/service-desk-racf/archive/dev-racf-full.zip"
      dest: "/var/www/html/"
      creates: "/var/www/html/service-desk-racf"
      remote_src: yes
    environment:
      https_proxy: http://10.2.75.44:3128

  - name: Set permission on Smarty template cache
    file:
      path: /var/www/html/service-desk-racf-dev-racf-full/templates_c
      owner: apache
      setype: httpd_sys_rw_content_t
      state: directory

  - name: fix path to Smarty in config file
    lineinfile:
      dest: /var/www/html/service-desk-racf-dev-racf-full/conf/config.inc.php
      regexp: "SMARTY"
      line: define("SMARTY", "/usr/share/php/Smarty/Smarty.class.php");

  - name: create config.inc.local.php for self-service-password
    template:
      src: self-service-password/config.inc.local.php.j2
      dest: /var/www/html/self-service-password-racf-master/conf/config.inc.local.php

  - name: create config.inc.local.php for service-desk-racf
    template:
      src: service-desk-racf/config.inc.local.php.j2
      dest: /var/www/html/service-desk-racf-dev-racf-full/conf/config.inc.local.php

- name: permit SELinux access to LDAP from Apache
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: yes

- name: restart httpd
  service:
    name: httpd.service
    state: restarted
    enabled: yes

