---
- name: generate z/VM private key
  openssl_privatekey:
    path: /etc/pki/tls/private/zVM.pem

- name: generate z/VM CSR
  openssl_csr:
    path: /etc/pki/tls/misc/zVM.csr
    privatekey_path: /etc/pki/tls/private/zVM.pem
    common_name: "zVM.{{ cluster_name }}.{{ cluster_base_domain }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "IBM z/VM for Red Hat Openshift PoC"
    country_name: "{{ cert_country }}"

- name: generate Certificate
  openssl_certificate:
    path: /etc/pki/tls/certs/zVM.cert
    csr_path: /etc/pki/tls/misc/zVM.csr
    ownca_path: /etc/pki/tls/certs/oqsCA.cert
    ownca_privatekey_path: /etc/pki/tls/private/oqsCA.pem
    provider: ownca

- name: Generate PKCS12 file
  openssl_pkcs12:
    action: export
    path: /etc/pki/tls/certs/zVM.p12
    friendly_name: zVMTLS
    privatekey_path: /etc/pki/tls/private/zVM.pem
    certificate_path: /etc/pki/tls/certs/zVM.cert
    other_certificates: /etc/pki/tls/certs/oqsCA.cert
    passphrase: zvm4demo
    state: present

- name: generate z/VM LDAP private key
  openssl_privatekey:
    path: /etc/pki/tls/private/zVMLDAP.pem

- name: generate z/VM LDAP CSR
  openssl_csr:
    path: /etc/pki/tls/misc/zVMLDAP.csr
    privatekey_path: /etc/pki/tls/private/zVMLDAP.pem
    common_name: "LDAPSRV.{{ cluster_name }}.{{ cluster_base_domain }}"
    organization_name: "{{ cert_organization }}"
    organizational_unit_name: "IBM z/VM for Red Hat Openshift PoC"
    country_name: "{{ cert_country }}"

- name: generate Certificate
  openssl_certificate:
    path: /etc/pki/tls/certs/zVMLDAP.cert
    csr_path: /etc/pki/tls/misc/zVMLDAP.csr
    ownca_path: /etc/pki/tls/certs/oqsCA.cert
    ownca_privatekey_path: /etc/pki/tls/private/oqsCA.pem
    provider: ownca

- name: Generate PKCS12 file
  openssl_pkcs12:
    action: export
    path: /etc/pki/tls/certs/zVMLDAP.p12
    friendly_name: LDAPSRV
    privatekey_path: /etc/pki/tls/private/zVMLDAP.pem
    certificate_path: /etc/pki/tls/certs/zVMLDAP.cert
    other_certificates: /etc/pki/tls/certs/oqsCA.cert
    passphrase: zvm4demo
    state: present

